telemetry = false

[test]
preload = ["./tests/setup.ts", "./tests/dom-helper/index.ts"]
coveragePathIgnorePatterns = [
    "**/*.test.ts",
    "tests/**",
]
coverageThreshold = 0.80
coverageSkipTestFiles = true
